### ISSUE TITLE
Problems with new version of nvisii for loading single objects

### ISSUE THREAD

**Issue by Branden-Kang** [NVlabs/Deep_Object_Pose#207]
Hello,

Thank you for your hard work on DOPE and NVISII.
I have a question about NVISII. I used the command yesterday: `python single_video_pybullet.py --path_single_obj models/Ketchup/google_16k/textured.obj --nb_frames 10`
But, I got an error below:

loading: models/Ketchup/google_16k/textured.obj
Traceback (most recent call last):
  File "single_video_pybullet.py", line 516, in <module>
    visii.entity.get(entry['visii_id']).get_transform().get_parent().set_position(
AttributeError: 'NoneType' object has no attribute 'set_position'
CUDA call (cudaGetDevice(&savedActiveDeviceID)) failed with code 4 (line 145): driver shutting down
terminate called after throwing an instance of 'std::runtime_error'
  what():  fatal cuda error
Aborted (core dumped)

Now, thanks to Jonathan, it works now when I typed the command: `python single_video_pybullet.py --path_single_obj models/Ketchup/google_16k/textured.obj --nb_frames 10 --nb_objects 4 **--nb_distractors 0** --scale_single_obj 0.04 `

When you check the code, adding_mesh_object function is changed.

However, there was still an error when I used the command: `python single_video_pybullet.py --path_single_obj models/Ketchup/google_16k/textured.obj --nb_frames 10 --nb_objects 4 **--nb_distractors 1** --scale_single_obj 0.04 `

I just added nb_distractors parameter. The codes worked well without nb_distractors. I am fixing the codes.

I used the command: `python single_video_pybullet.py --path_single_obj models/Ketchup/google_16k/textured.obj --nb_frames 10 --nb_objects 4 --nb_distractors 4 --scale_single_obj 0.01`

I got an error message below:

pybullet build time: Dec  1 2021 18:32:25
folder output/ exists
folder output/output_example// exists
Warning, create_perspective_from_fov is deprecated and will be removed in a subsequent release. Please switch to create_from_fov.
loading: google_scanned_models/Perricoen_MD_No_Concealer_Concealer//meshes/model.obj
loading: google_scanned_models/Black_Decker_Stainless_Steel_Toaster_4_Slice//meshes/model.obj
loading: google_scanned_models/Perricone_MD_Chia_Serum//meshes/model.obj
loading: google_scanned_models/Google_Cardboard_Original_package//meshes/model.obj
loading: models/Ketchup/google_16k/textured.obj
loading: models/Ketchup/google_16k/textured.obj
loading: models/Ketchup/google_16k/textured.obj
loading: models/Ketchup/google_16k/textured.obj
update {'visii_id': 'google_Perricoen_MD_No_Concealer_Concealer_0', 'bullet_id': 0, 'base_rot': None}
Traceback (most recent call last):
  File "single_video_pybullet.py", line 525, in <module>
    visii.entity.get(entry['visii_id']).get_transform().get_parent().set_position(
AttributeError: 'NoneType' object has no attribute 'set_position'
CUDA call (cudaGetDevice(&savedActiveDeviceID)) failed with code 4 (line 145): driver shutting down
terminate called after throwing an instance of 'std::runtime_error'
  what():  fatal cuda error
Aborted (core dumped)

google_scanned_models/Perricoen_MD_No_Concealer_Concealer//meshes/model.obj is loaded successfully but google_scanned_models/Black_Decker_Stainless_Steel_Toaster_4_Slice//meshes/model.obj is missing.

Therefore, I think that adding_mesh_object function has to be fixed.

**Comment by TontonTremblay** [comment]
Yeah You are probably right, I added a if and else based on some condition that was pretty hacky. It should be an easy fix. I think you wanted to have a chance to send a PR, so I will not fix it yet.
