### ISSUE TITLE
Cannot find the camera_setting.json file for shiny meat dataset made in Nvisii

### ISSUE THREAD

**Issue by monajalal** [NVlabs/Deep_Object_Pose#275]
I found the shiny meat dataset in train2 folder however, when I am trying to do inference, it is requiring the camera setting in json format. Could you please provide the camera setting file for it?

```
~/research/dope/scripts/train2/out_experiment$ nvdu_viz .
args: Namespace(auto_change=False, auto_export=False, camera_settings_path=None, data_annot_dir='', dataset_dir='.', export_dir='', fps=10, ignore_fixed_transform=False, name_filters=['*.png'], object_settings_path=None, size=[0, 0])
name_filters: ['*.png']
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/DOPE/bin/nvdu_viz", line 8, in <module>
    sys.exit(main())
  File "/home/mona/anaconda3/envs/DOPE/lib/python3.8/site-packages/nvdu/tools/test_nvdu_visualizer.py", line 92, in main
    camera_intrinsic_settings = CameraIntrinsicSettings.from_json_file(camera_settings_path)
  File "/home/mona/anaconda3/envs/DOPE/lib/python3.8/site-packages/nvdu/core/camera.py", line 86, in from_json_file
    with open(json_file_path, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: './_camera_settings.json'
```

Here's the shiny meat dataset you shared: https://drive.google.com/file/d/1Q5VLnlt1gu2pKIAcUo9uzSyWw1nGlSF8/view?usp=sharing

**Comment by TontonTremblay** [comment]
yeah the data I generated from the nvisii data generation script are not compatible with nvdu, sorry. It would not be too hard to look at the data in the json files to create a _camera_settings.json though.
